version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000" # Express backend
      - "5173:5173" # Vite dev server
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run start
